
name: "build"

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: G11n Analysis
      uses: gosp/resource-checker@v1.2
      with:
          languages: en-US fr-FR

    - name: Actifacts publish
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: g11n-result
        path: detail.csv
